### ISSUE TITLE
Linux: Failed to Build (Undefined reference to fcntl64@GLIBC_2.28

### ISSUE THREAD

**Issue by dsamt** [alexmercerind/dart_vlc#66]
Hi I am trying to use this plugin and have struggled to get it to compile using Ubuntu 20.04. I believe I have all the proper dependencies installed for vlc, and after trying may solutions I am still stuck. I am hoping you may be able to find the problems I am having. Below is my full log. Thank you.

:~/Desktop/new_menu$ flutter run -d "Linux" --verbose
[  +57 ms] executing: [/home/daniel/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[    	] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[    	] executing: [/home/daniel/snap/flutter/common/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +15 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[    	] 2.0.6
[  +67 ms] executing: [/home/daniel/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[    	] origin/stable
[    	] executing: [/home/daniel/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[    	] https://github.com/flutter/flutter.git
[  +92 ms] executing: [/home/daniel/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +167 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +146 ms] executing: /home/daniel/Android/Sdk/platform-tools/adb devices -l
[  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[    	] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] executing: /home/daniel/Android/Sdk/platform-tools/adb devices -l
[  +22 ms] Skipping pub get: version match.
[  +52 ms] Found plugin audioplayers at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/
[  +33 ms] Found plugin dart_vlc at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[  +22 ms] Found plugin path_provider at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +2 ms] Found plugin path_provider_linux at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_macos at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +3 ms] Found plugin path_provider_windows at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[ +193 ms] Found plugin audioplayers at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.18.3/
[  +17 ms] Found plugin dart_vlc at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[  +18 ms] Found plugin path_provider at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +4 ms] Found plugin path_provider_linux at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_macos at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +8 ms] Found plugin path_provider_windows at /home/daniel/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[  +52 ms] Generating /home/daniel/Desktop/new_menu/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +257 ms] Initializing file store
[  +32 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +9 ms] Launching lib/main.dart on Linux in debug mode...
[  +12 ms] /home/daniel/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/daniel/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/daniel/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
--output-dill /tmp/flutter_tools.WCMKHI/flutter_tool.HXQZQZ/app.dill --packages /home/daniel/Desktop/new_menu/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +86 ms] Building Linux application...
[  +94 ms] <- compile package:new_menu/main.dart
[  +27 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/daniel/Desktop/new_menu/linux
[  +59 ms] List of devices attached
[  +14 ms] List of devices attached
[ +391 ms] -- Configuring done
[   +8 ms] -- Generating done
[    	] -- Build files have been written to: /home/daniel/Desktop/new_menu/build/linux/debug
[   +6 ms] executing: ninja -C build/linux/debug install
[  +54 ms] ninja: Entering directory `build/linux/debug'
[ +688 ms] [1/8] Running utility command for LIBVLC_EXTRACT
[+10103 ms] [2/8] Generating /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/daniel/Desktop/new_menu/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +11 ms] [ +273 ms] executing: [/home/daniel/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [ +194 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[    	] [    	] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +2 ms] [    	] executing: [/home/daniel/snap/flutter/common/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[    	] [  +33 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[    	] [    	] 2.0.6
[    	] [ +138 ms] executing: [/home/daniel/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[    	] [  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[    	] [    	] origin/stable
[    	] [    	] executing: [/home/daniel/snap/flutter/common/flutter/] git ls-remote --get-url origin
[    	] [  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[   +7 ms] [    	] https://github.com/flutter/flutter.git
[   +2 ms] [ +176 ms] executing: [/home/daniel/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[    	] [    	] stable
[    	] [ +265 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[    	] [   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[    	] [   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[    	] [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [    	] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[    	] [ +212 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[    	] [   +7 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[    	] [    	] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[    	] [    	] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [    	] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[    	] [   +6 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[    	] [    	] Artifact Instance of 'PubDependencies' is not required, skipping update.
[    	] [ +390 ms] Initializing file store
[    	] [  +32 ms] Done initializing file store
[    	] [  +77 ms] Skipping target: gen_localizations
[    	] [+3294 ms] Skipping target: unpack_linux
[    	] [+1168 ms] Skipping target: kernel_snapshot
[   +5 ms] [ +653 ms] Skipping target: debug_bundle_linux_assets
[   +4 ms] [   +1 ms] Persisting file store
[    	] [  +26 ms] Done persisting file store
[    	] [  +29 ms] build succeeded.
[    	] [  +14 ms] "flutter assemble" took 6,061ms.
[    	] [ +243 ms] ensureAnalyticsSent: 233ms
[    	] [   +1 ms] Running shutdown hooks
[    	] [    	] Shutdown hooks complete
[    	] [    	] exiting with code 0
[+1231 ms] [3/6] Building CXX object CMakeFiles/new_menu.dir/flutter/generated_plugin_registrant.cc.o
[ +119 ms] [4/6] Building CXX object CMakeFiles/new_menu.dir/my_application.cc.o
[ +361 ms] [5/6] Linking CXX executable intermediates_do_not_run/new_menu
[   +7 ms] FAILED: intermediates_do_not_run/new_menu
[  +12 ms] : && /snap/flutter/current/usr/bin/clang++  -g  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma
-lpthread -L/snap/flutter/current/usr/lib/ -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread
-L/snap/flutter/current/usr/lib/ CMakeFiles/new_menu.dir/main.cc.o CMakeFiles/new_menu.dir/my_application.cc.o CMakeFiles/new_menu.dir/flutter/generated_plugin_registrant.cc.o  -o
intermediates_do_not_run/new_menu  -Wl,-rpath,/home/daniel/Desktop/new_menu/build/linux/debug/plugins/dart_vlc:/home/daniel/Desktop/new_menu/linux/flutter/ephemeral:
plugins/dart_vlc/libdart_vlc_plugin.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so /home/daniel/Desktop/new_menu/linux/flutter/ephemeral/libflutter_linux_gtk.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libblkid.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/liblzma.so && :
[  +16 ms] //lib/x86_64-linux-gnu/libvlccore.so.9: undefined reference to `fcntl64@GLIBC_2.28'
[    	] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +8 ms] ninja: build stopped: subcommand failed.
[  +81 ms] Building Linux application... (completed in 13.3s)
[+4903 ms] Exception: Build process failed
[   +6 ms] "flutter run" took 19,482ms.
[   +3 ms]
       	#0  	throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
       	#1  	RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
       	<asynchronous suspension>
       	#2  	FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
       	<asynchronous suspension>
       	#3  	FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
       	<asynchronous suspension>
       	#4  	AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
       	<asynchronous suspension>
       	#5  	AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
       	<asynchronous suspension>
       	#6  	CommandRunner.runCommand (package:args/command_runner.dart:197:13)
       	<asynchronous suspension>
       	#7  	FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
       	<asynchronous suspension>
       	#8  	AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
       	<asynchronous suspension>
       	#9  	AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
       	<asynchronous suspension>
       	#10 	FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
       	<asynchronous suspension>
       	#11 	run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
       	<asynchronous suspension>
       	#12 	run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
       	<asynchronous suspension>
       	#13 	AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
       	<asynchronous suspension>
       	#14 	AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
       	<asynchronous suspension>
       	#15 	runInContext (package:flutter_tools/src/context_runner.dart:73:10)
       	<asynchronous suspension>
       	#16 	main (package:flutter_tools/executable.dart:90:3)
       	<asynchronous suspension>
      	 
      	 
[ +106 ms] ensureAnalyticsSent: 96ms
[    	] Running shutdown hooks
[    	] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
[    	] exiting with code 1

**Comment by dsamt** [comment]
@stonega @mfkl @jonafeucht @alexmercerind any support?

**Comment by alexmercerind** [comment]
@dsamt Undefined reference means that your machine is missing any shared library. Stack overflow will be better place to ask this.

**Comment by dsamt** [comment]
Yes I have built multiple applications on my system the only time I run into problems is with this plugin. I am running Flutter 2.2.1 on Ubuntu 20.04.

**Comment by alexmercerind** [comment]
@dsamt maybe https://github.com/flutter/flutter/issues/64348

**Comment by dsamt** [comment]
I believe the error was caused by whatever missing libraries come with the snap version of flutter and was fixed by just reinstalling flutter with the git repository.
